// ============================================================================
// IndexedDB schema types for AI-CHATKIT local storage
// ============================================================================

/** Matches the existing UI Message interface */
export interface ChatSessionRecord {
  threadId: string;
  name: string;
  agentId: string;
  createdAt: number;
  updatedAt: number;
  lastMessagePreview: string;
}

export interface ChatMessageRecord {
  id: string;
  threadId: string;
  type: "user" | "ai" | "tool";
  content: string;
  /** References into the assets store — replaces inline base64 data URLs */
  imageAssetIds?: string[];
  /** Reserved for future generated-image workflows */
  generatedAssetIds?: string[];
  toolCall?: { calls: any[] };
  createdAt: number;
  updatedAt: number;
}

export interface AssetRecord {
  id: string;
  threadId: string;
  kind: "user_upload" | "generated_image";
  mimeType: string;
  blob: Blob;
  size: number;
  createdAt: number;
  /** "input" = user-uploaded; "jimeng" = generated by Jimeng */
  source?: "input" | "jimeng";
  /** The original prompt that produced this image (generated only) */
  prompt?: string;
  /** Remote CDN / OSS URL (generated only) */
  remoteUrl?: string;
  /** Arbitrary extra metadata */
  metadata?: Record<string, any>;
}

export interface PendingMessageRecord {
  threadId: string;
  message: string;
  imageAssetIds?: string[];
  agentId: string;
  createdAt: number;
}
